### ISSUE TITLE
Keep OpenAI API for non eligible countries ?

### ISSUE THREAD

**Issue by Quentin-Sch** [Welltested-AI/fluttergpt#122]
Hello and thanks for your work !
Gemini is not available worldwide (for exemple in France we can't access the API without VPN)
Is it possible to keep the previous way of working for users like us ? With open AI API ?

Thank you

**Comment by samyakkkk** [comment]
Thanks for highlighting the issue @Quentin-Sch. 

While maintaining support for OpenAI can be considered, a simple solution for now is to install the old version only (0.0.11): 

<img width="541" alt="Screenshot 2023-12-24 at 5 39 50 AM" src="https://github.com/Welltested-AI/fluttergpt/assets/56000318/95ad0d49-0af5-450b-ac17-f98404f74440">

We can check Google's plan for making Gemini available worldwide (which I'm assuming should be very soon) and prepare a roadmap accordingly. 

Thanks again for reporting! I'm keeping this thread open since it will be helpful to many.
