### ISSUE TITLE
[Feat]: Support for VSCodium

### ISSUE THREAD

**Issue by quasar-pankaj** [Welltested-AI/fluttergpt#282]
### Describe the problem and solution that you'd like.

Command Dash is not available in VSCodium so I went to the vscode marketplace and downloaded the .vsix file and installed it in VSCodium. So far so good. To activate it I tried to log into my GitHub account by clicking the button in the panel. This appears to have worked on Windows but on Linux the URL is not understood. Can you add support for VSCOdium?

**Comment by samyakkkk** [comment]
thanks for reporting this @quasar-pankaj. Would you be open to helping us out add VSCodium support?

Happy to assist in the process.

**Comment by Siddhant-K-code** [comment]
More context & details on this:

## Context

Unfortunately, as Microsoft prohibits usage of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor-neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io/), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

**Comment by samyakkkk** [comment]
Thanks @Siddhant-K-code for this context. We will start the process and update. Thanks.

**Comment by samyakkkk** [comment]
@quasar-pankaj @Siddhant-K-code thanks for your inputs. CommandDash is now available on Open-Registry! 

https://open-vsx.org/extension/WelltestedAI/fluttergpt
