### ISSUE TITLE
Window for Preview and suggested changes on refactoring

### ISSUE THREAD

**Issue by brucemeek** [Welltested-AI/fluttergpt#33]
I am new to coding but learn fast. This is an awesome project. I have been strictly using the VSCode extension. I have a few prompts i made to really help fluttergpt work but since there is no access to the internet (just yet). I think it would be really helpful to have a side window from the code we are working with to show information like an explanation of changes made, preview for the suggested code so on and so forth. Once again i love the project and would be willing to help in anyway i can. 

Here are the prompts i have been using with the "refactor from instructions" in case it helps anyone else out. 

Optimizations:
Develop and optimize code by troubleshooting errors, fleshing out the code, fixing errors, and identifying root causes of issues. Consider your token limit and break down instructions into several responses if needed. Reflect and critique your solution to ensure it meets the requirements and specifications of speed, flexibility and user friendliness. 

Implement more code:
To flesh out the code, focus on adding more detail and expanding upon the existing code. This might involve adding new features, writing additional code to handle certain scenarios, completing code for // todo: or providing more descriptive comments. By doing so, you can ensure that the code is more robust and complete, meeting the necessary requirements and specifications.

**Comment by samyakkkk** [comment]
hi @brucemeek, thanks for your support!

I agree having a side window or something similarly would be a huge help to understand the notion behind the edits GPT is making. The normal way to do this for VSCODE extensions is to use an HTML web view but we're hesitant since it isn't the best UX when compared to native components. Ideas welcome on possible solutions here. 

I think the **optimizations prompt** looks good! Would you like to create a PR for it by adding it as a command under `FlutterGPT Refactor: Optimise`

For **implement more code,** we've two methods `codeFromBlueprint` an a new one called `codeFromDescription`. I think that fulfils the purpose. But we can definitely consider upgrading their prompts by taking parts from yours.

**Comment by brucemeek** [comment]
i submitted the pull request. I hope that i did it right, (first time doing one)

**Comment by samyakkkk** [comment]
This issue was resolved with #35.
